#!/bin/bash

s6-svok /etc/s6/consul

case "$?" in
	0)
		echo "Monitoring consul, continuing"
		;;
	1)
		echo "Monitoring failed ... restarting"
		exit 1
		;;
esac

s6-svwait -U /etc/s6/consul

if [ "$VOL" == "any" ]
then
	export VOL="default"
fi

#exec s6-notifywhenup syncthing -gui-address="0.0.0.0:8080" -no-browser | tee /dev/stderr
exec s6-notifywhenup -d 2 ./creature.sh